CREATE DATABASE E_MEDICAL;

CREATE TABLE LONGIN_DETAILES
(
USERNAME VARCHAR(50) NOT NULL,
PASS NVARCHAR(50) NOT NULL
);

CREATE TABLE AMBULANCE
(
NAME VARCHAR(50) NOT NULL,
AGE INT,
ADDRES VARCHAR(50) NOT NULL,
STREET VARCHAR(50) NOT NULL,
HOUSE_NO VARCHAR(50),
PHONE VARCHAR(50)NOT NULL
);

CREATE TABLE MEDICINE
(
NAME VARCHAR(50) NOT NULL,
AGE INT,
ADDRES VARCHAR(50) NOT NULL,
STREET VARCHAR(50) NOT NULL,
HOUSE_NO VARCHAR(50),
MED_NAME VARCHAR(50) NOT NULL,
QUANTITY INT,
PHONE VARCHAR(50)NOT NULL,
);

CREATE TABLE DOCTOR
(
NAME VARCHAR(50) NOT NULL,
AGE INT,
ADDRES VARCHAR(50) NOT NULL,
STREET VARCHAR(50) NOT NULL,
HOUSE_NO VARCHAR(50),
PHONE VARCHAR(50)NOT NULL,
PROBLEMS VARCHAR(1000)NOT NULL
);

CREATE TABLE REG
(
f_NAME VARCHAR(50)NOT NULL,
L_NAME VARCHAR(50)NOT NULL,
EMAIL VARCHAR(50),
AGE INT,
ADDRES VARCHAR(50) NOT NULL,
PHONE VARCHAR(50)NOT NULL,
USERNAME VARCHAR(50)NOT NULL,
PASS VARCHAR(50)NOT NULL 
);

SELECT* FROM LONGIN_DETAILES;
SELECT * FROM AMBULANCE;
SELECT * FROM MEDICINE;
SELECT * FROM DOCTOR;
SELECT * FROM REG;
